.TH "Referencia del directorio src" 3 "Sábado, 30 de Abril de 2016" "Practica 3 - Redes de Comunicaciones II" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Referencia del directorio src \- 
.SH SYNOPSIS
.br
.PP
.SS "Archivos"

.in +1c
.ti -1c
.RI "archivo \fBG\-2301\-01\-P1\-irc_server\&.c\fP"
.br
.RI "\fIServidor IRC\&. \fP"
.ti -1c
.RI "archivo \fBG\-2301\-01\-P3\-ssl_client\&.c\fP"
.br
.RI "\fICliente de echo SSL\&. \fP"
.ti -1c
.RI "archivo \fBG\-2301\-01\-P3\-ssl_echo_server\&.c\fP"
.br
.RI "\fIServidor de echo SSL\&. \fP"
.ti -1c
.RI "archivo \fBxchat2\&.c\fP"
.br
.RI "\fIPrograma principal del cliente IRC\&. \fP"
.in -1c
