.TH "src/G-2301-01-P3-ssl_echo_server.c" 3 "Sábado, 30 de Abril de 2016" "Practica 3 - Redes de Comunicaciones II" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/G-2301-01-P3-ssl_echo_server.c \- Servidor de echo SSL\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'G\-2301\-01\-P3\-ssl\-server\&.h'\fP
.br
\fC#include 'G\-2301\-01\-P3\-ssl\&.h'\fP
.br
\fC#include <G\-2301\-01\-P1\-daemon\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <syslog\&.h>\fP
.br

.SS "Funciones"

.in +1c
.ti -1c
.RI "void * \fBecho\fP (void *data)"
.br
.RI "\fIFuncion de atencion a las conexiones\&. \fP"
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.RI "\fILlamada principal del servidor\&. \fP"
.in -1c
.SH "Descripción detallada"
.PP 
Servidor de echo SSL\&. 


.PP
\fBAutor:\fP
.RS 4
Sergio Fuentes sergio.fuentesd@estudiante.uam.es 
.PP
Daniel Perdices daniel.perdices@estudiante.uam.es 
.RE
.PP
\fBFecha:\fP
.RS 4
2016/04/28 
.RE
.PP

.PP
Definición en el archivo \fBG\-2301\-01\-P3\-ssl_echo_server\&.c\fP\&.
.SH "Documentación de las funciones"
.PP 
.SS "void* echo (void * data)"

.PP
Funcion de atencion a las conexiones\&. 
.PP
\fBParámetros:\fP
.RS 4
\fIdata\fP Datos recibidos y de la conexion 
.RE
.PP
\fBDevuelve:\fP
.RS 4
Ningún valor definido, la función controla el error de manera interna 
.RE
.PP

.PP
Definición en la línea 20 del archivo G\-2301\-01\-P3\-ssl_echo_server\&.c\&.
.PP
Hace referencia a connection_unblock_SSL() y enviar_datos_SSL()\&.
.SS "int main (int argc, char ** argv)"

.PP
Llamada principal del servidor\&. 
.PP
\fBParámetros:\fP
.RS 4
\fIargc\fP Num de argumentos 
.br
\fIargv\fP Argumentos 
.RE
.PP
\fBDevuelve:\fP
.RS 4
0 
.RE
.PP

.PP
Definición en la línea 42 del archivo G\-2301\-01\-P3\-ssl_echo_server\&.c\&.
.PP
Hace referencia a daemonize(), echo() y server_launch_SSL()\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Practica 3 - Redes de Comunicaciones II del código fuente\&.
