.TH "srclib/G-2301-01-P1-server.c" 3 "Viernes, 29 de Abril de 2016" "Practica 2 - Redes de Comunicaciones II" \" -*- nroff -*-
.ad l
.nh
.SH NAME
srclib/G-2301-01-P1-server.c \- 
.PP
Libreria de manejo de un servidor de sockets\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <pthread\&.h>\fP
.br
\fC#include <sys/types\&.h>\fP
.br
\fC#include <sys/socket\&.h>\fP
.br
\fC#include <netinet/in\&.h>\fP
.br
\fC#include <sys/select\&.h>\fP
.br
\fC#include <sys/time\&.h>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <strings\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <signal\&.h>\fP
.br
\fC#include <arpa/inet\&.h>\fP
.br
\fC#include <G-2301-01-P1-tcp\&.h>\fP
.br
\fC#include 'G-2301-01-P1-server\&.h'\fP
.br

.SS "Funciones"

.in +1c
.ti -1c
.RI "int \fBconnection_add\fP (int socketd)"
.br
.RI "\fIAñade una conexion al conjunto del select\&. \fP"
.ti -1c
.RI "int \fBconnection_rmv\fP (int socketd)"
.br
.RI "\fIBorra una conexion del conjunto del select\&. \fP"
.ti -1c
.RI "int \fBis_connected\fP (int socketd)"
.br
.RI "\fIIndica si hay una conexion abierta\&. \fP"
.ti -1c
.RI "int \fBis_readable\fP (int socketd)"
.br
.RI "\fIIndica si hay una conexion que requiere atencion\&. \fP"
.ti -1c
.RI "int \fBconnection_block\fP (int socketd)"
.br
.RI "\fIBloquea una conexion\&. \fP"
.ti -1c
.RI "int \fBconnection_unblock\fP (int socketd)"
.br
.RI "\fIDesbloquea una conexion\&. \fP"
.ti -1c
.RI "int \fBconnection_isblocked\fP (int socketd)"
.br
.RI "\fIComprueba si una conexion esta bloqueada\&. \fP"
.ti -1c
.RI "char * \fBget_ip_from_connection\fP (int socketd)"
.br
.RI "\fIDevuelve la ip asociada a un socked\&. \fP"
.ti -1c
.RI "void \fBsigint_handler\fP (int sig)"
.br
.RI "\fIManejador de la señal\&. \fP"
.ti -1c
.RI "int \fBserver_launch\fP (uint16_t port, void *(*\fBhandler\fP)(void *), void *more)"
.br
.RI "\fILanza un servidor que atiende cada mensaje recibido con la funcion handler\&. \fP"
.ti -1c
.RI "int \fBserver_stop\fP ()"
.br
.RI "\fIPara el servidor TCP\&. \fP"
.ti -1c
.RI "int \fBset_do_on_disconnect\fP (void(*\fBhandler\fP)(void *))"
.br
.RI "\fIPara el servidor TCP\&. \fP"
.in -1c
.SH "Descripción detallada"
.PP 
Libreria de manejo de un servidor de sockets\&. 

Libreria de manejo de un servidor de sockets SSL\&.
.PP
\fBAutor:\fP
.RS 4
Sergio Fuentes sergio.fuentesd@estudiante.uam.es 
.PP
Daniel Perdices daniel.perdices@estudiante.uam.es 
.RE
.PP
\fBFecha:\fP
.RS 4
2016/02/01 
.RE
.PP

.PP
Definición en el archivo \fBG-2301-01-P1-server\&.c\fP\&.
.SH "Documentación de las funciones"
.PP 
.SS "int connection_add (intsocketd)"

.PP
Añade una conexion al conjunto del select\&. 
.PP
\fBParámetros:\fP
.RS 4
\fIsocketd\fP Descriptor del socket 
.RE
.PP
\fBDevuelve:\fP
.RS 4
SERVOK 
.RE
.PP

.PP
Definición en la línea 36 del archivo G-2301-01-P1-server\&.c\&.
.SS "int connection_block (intsocketd)"

.PP
Bloquea una conexion\&. 
.PP
\fBParámetros:\fP
.RS 4
\fIsocketd\fP Descriptor del socket 
.RE
.PP
\fBDevuelve:\fP
.RS 4
SERVOK 
.RE
.PP

.PP
Definición en la línea 86 del archivo G-2301-01-P1-server\&.c\&.
.SS "int connection_isblocked (intsocketd)"

.PP
Comprueba si una conexion esta bloqueada\&. 
.PP
\fBParámetros:\fP
.RS 4
\fIsocketd\fP Descriptor del socket 
.RE
.PP
\fBDevuelve:\fP
.RS 4
0 si no esta bloqueada, otro valor si esta bloqueada 
.RE
.PP

.PP
Definición en la línea 110 del archivo G-2301-01-P1-server\&.c\&.
.SS "int connection_rmv (intsocketd)"

.PP
Borra una conexion del conjunto del select\&. 
.PP
\fBParámetros:\fP
.RS 4
\fIsocketd\fP Descriptor del socket 
.RE
.PP
\fBDevuelve:\fP
.RS 4
SERVOK 
.RE
.PP

.PP
Definición en la línea 48 del archivo G-2301-01-P1-server\&.c\&.
.SS "int connection_unblock (intsocketd)"

.PP
Desbloquea una conexion\&. 
.PP
\fBParámetros:\fP
.RS 4
\fIsocketd\fP Descriptor del socket 
.RE
.PP
\fBDevuelve:\fP
.RS 4
SERVOK 
.RE
.PP

.PP
Definición en la línea 98 del archivo G-2301-01-P1-server\&.c\&.
.SS "char* get_ip_from_connection (intsocketd)"

.PP
Devuelve la ip asociada a un socked\&. 
.PP
\fBParámetros:\fP
.RS 4
\fIsocketd\fP Descriptor del socket 
.RE
.PP
\fBDevuelve:\fP
.RS 4
La ip del socket en decimal 
.RE
.PP

.PP
Definición en la línea 123 del archivo G-2301-01-P1-server\&.c\&.
.SS "int is_connected (intsocketd)"

.PP
Indica si hay una conexion abierta\&. 
.PP
\fBParámetros:\fP
.RS 4
\fIsocketd\fP Descriptor del socket 
.RE
.PP
\fBDevuelve:\fP
.RS 4
0 si esta cerrada, cualquier valor en otro caso 
.RE
.PP

.PP
Definición en la línea 60 del archivo G-2301-01-P1-server\&.c\&.
.SS "int is_readable (intsocketd)"

.PP
Indica si hay una conexion que requiere atencion\&. 
.PP
\fBParámetros:\fP
.RS 4
\fIsocketd\fP Descriptor del socket 
.RE
.PP
\fBDevuelve:\fP
.RS 4
0 si esta cerrada, cualquier valor en otro caso 
.RE
.PP

.PP
Definición en la línea 73 del archivo G-2301-01-P1-server\&.c\&.
.SS "int server_launch (uint16_tport, void *(*)(void *)handler, void *more)"

.PP
Lanza un servidor que atiende cada mensaje recibido con la funcion handler\&. 
.PP
\fBParámetros:\fP
.RS 4
\fIport\fP Puerto en el que abrir el servidor 
.br
\fIhandler\fP Rutina de atencion de los mensajes 
.br
\fImore\fP Parametros adicionales que se necesiten en la rutina de atencion 
.RE
.PP
\fBDevuelve:\fP
.RS 4
SERVOK en caso de que el servidor termine correctamente un numero negativo en caso de error 
.RE
.PP

.PP
Definición en la línea 146 del archivo G-2301-01-P1-server\&.c\&.
.PP
Hace referencia a connection_add(), connection_block(), connection_isblocked(), connection_rmv(), handler(), is_readable(), server_stop(), server_tcpsocket_open(), sigint_handler(), tcpsocket_accept(), tcpsocket_close() y tcpsocket_rcv()\&.
.SS "int server_stop ()"

.PP
Para el servidor TCP\&. 
.PP
\fBDevuelve:\fP
.RS 4
SERVOK si el servidor se para, SERVERR_NRUN si no hay servidor 
.RE
.PP

.PP
Definición en la línea 249 del archivo G-2301-01-P1-server\&.c\&.
.SS "int set_do_on_disconnect (void(*)(void *)handler)"

.PP
Para el servidor TCP\&. 
.PP
\fBDevuelve:\fP
.RS 4
SERVOK si el servidor se para, SERVERR_NRUN si no hay servidor 
.RE
.PP

.PP
Definición en la línea 263 del archivo G-2301-01-P1-server\&.c\&.
.PP
Hace referencia a handler()\&.
.SS "void sigint_handler (intsig)"

.PP
Manejador de la señal\&. 
.PP
\fBParámetros:\fP
.RS 4
\fIsig\fP señal recibido 
.RE
.PP
\fBDevuelve:\fP
.RS 4
0 si no esta bloqueada, otro valor si esta bloqueada 
.RE
.PP

.PP
Definición en la línea 133 del archivo G-2301-01-P1-server\&.c\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Practica 2 - Redes de Comunicaciones II del código fuente\&.
