.TH "src/G-2301-01-P3-ssl_client.c" 3 "Domingo, 1 de Mayo de 2016" "Practica 3 - Redes de Comunicaciones II" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/G-2301-01-P3-ssl_client.c \- Cliente de echo SSL\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <G\-2301\-01\-P1\-tcp\&.h>\fP
.br
\fC#include <G\-2301\-01\-P3\-ssl\&.h>\fP
.br

.SS "Funciones"

.in +1c
.ti -1c
.RI "void \fBshow_use\fP (int argc, char **argv)"
.br
.RI "\fIMuestra el uso del programa\&. \fP"
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.RI "\fILlamada principal del servidor\&. \fP"
.in -1c
.SH "Descripción detallada"
.PP 
Cliente de echo SSL\&. 


.PP
\fBAutor:\fP
.RS 4
Sergio Fuentes sergio.fuentesd@estudiante.uam.es 
.PP
Daniel Perdices daniel.perdices@estudiante.uam.es 
.RE
.PP
\fBFecha:\fP
.RS 4
2016/04/28 
.RE
.PP

.PP
Definición en el archivo \fBG\-2301\-01\-P3\-ssl_client\&.c\fP\&.
.SH "Documentación de las funciones"
.PP 
.SS "int main (int argc, char ** argv)"

.PP
Llamada principal del servidor\&. 
.PP
\fBParámetros:\fP
.RS 4
\fIargc\fP Num de argumentos 
.br
\fIargv\fP Argumentos 
.RE
.PP
\fBDevuelve:\fP
.RS 4
0 
.RE
.PP

.PP
Definición en la línea 26 del archivo G\-2301\-01\-P3\-ssl_client\&.c\&.
.PP
Hace referencia a cerrar_canal_SSL(), client_tcpsocket_open(), conectar_canal_seguro_SSL(), enviar_datos_SSL(), evaluar_post_connectar_SSL(), fijar_contexto_SSL(), inicializar_nivel_SSL(), liberar_nivel_SSL(), recibir_datos_SSL() y show_use()\&.
.SH "Autor"
.PP 
Generado automáticamente por Doxygen para Practica 3 - Redes de Comunicaciones II del código fuente\&.
